# Generated by Django 4.2.2 on 2023-07-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('department_image', models.ImageField(blank=True, null=True, upload_to='images/department/profile/')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/doctor/profiles/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.department'),
        ),
    ]
