# Generated by Django 4.2.2 on 2023-08-24 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_services'),
        ('doctor', '0005_alter_appointment_status'),
    ]

    operations = [
    ]
